modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Janitor/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbjanitor"
version = "${version}"
displayName = "FTB Janitor"
authors = "LatvianModder"
description = '''
Cleans up logs and fixes some bugs
'''

[[dependencies.ftbjanitor]]
modId = "forge"
mandatory = true
versionRange = "[32.0.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbjanitor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbjanitor]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1605.3.1-build.53,)"
ordering = "AFTER"
side = "BOTH"
