modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Janitor/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "ftbjanitor"
version = "${file.jarVersion}"
displayName = "FTB Janitor"
authors = "LatvianModder"
description = '''
Cleans up logs and fixes some bugs
'''
license = "All Rights Reserved"

[[dependencies.ftbjanitor]]
modId = "forge"
mandatory = true
versionRange = "[32.0.75,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbjanitor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
